# Python Basics for Understanding the Course Scripts

This notebook is a compact Python refresher for the methodsNET course on collecting data from online platforms.

It does **not** try to teach all of Python. It focuses on the Python ideas that appear again and again in the course scripts:

- variables and objects
- functions and arguments
- lists and dictionaries
- loops and indentation
- imports and packages
- file paths
- pandas DataFrames
- API responses and JSON
- BeautifulSoup selectors
- common error messages

Use this as a reference when reading the walkthrough scripts.

## How to Use This Notebook

Run cells from top to bottom.

In Jupyter or VS Code:

- click a code cell
- run it with the play button or `Shift + Enter`
- read the output below the cell

If the notebook starts behaving strangely, restart the kernel and run cells again from the top.

## 1. Python Files, Notebooks, and Scripts

In this course you will see three kinds of Python material:

| Format | What it is good for |
|---|---|
| `.ipynb` notebook | reading explanations and running code cell by cell |
| `.py` walkthrough | live coding and teaching step by step with `# %%` cells |
| runnable `.py` workflow | running a full workflow from the command line |

The same Python ideas appear in all three formats.

## 2. Comments and Docstrings

Python ignores comments. Comments explain the code to humans.

A line starting with `#` is a comment.

Triple quotes can create a longer text block. At the top of a file, this is often used as a docstring explaining what the script does.

In [1]:
# This is a comment. Python ignores it.

"""
This is a longer text block.
At the top of a script, it often explains the script's purpose.
"""

print("Comments are for humans; print() creates output.")

Comments are for humans; print() creates output.

## 3. Assignment and Variables

A variable is a name that points to a value.

The `=` sign means assignment: store the value on the right under the name on the left.

In [ ]:
query = "digital services act"
page_size = 50
source = "MediaWiki API"

print(query)
print(page_size)
print(source)

Variable names should be meaningful. In the course scripts, names such as `API_URL`, `params`, `headers`, `response`, and `payload` tell you what role the object plays.

In [ ]:
API_URL = "https://en.wikipedia.org/w/api.php"

print(API_URL)

## 4. Basic Data Types

Python objects have types. The most common ones in the course scripts are:

| Type | Example | Meaning |
|---|---|---|
| string | `"digital services act"` | text |
| integer | `50` | whole number |
| float | `1.5` | decimal number |
| boolean | `True` / `False` | yes/no value |
| None | `None` | missing/no value |

In [2]:
text_value = "digital services act"
number_value = 50
pause_seconds = 1.5
allowed = True
missing_value = None

print(type(text_value))
print(type(number_value))
print(type(pause_seconds))
print(type(allowed))
print(type(missing_value))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'NoneType'>

## 5. Functions

A function is reusable code that does something.

You call a function with parentheses.

In [ ]:
print("Hello")
len("digital services act")
type("digital services act")

Functions can take arguments. Some arguments are positional; others are named keyword arguments.

In the course scripts you often see keyword arguments such as `timeout=30`, `index=False`, or `strip=True`.

In [5]:
text = "   digital services act   "

print(text.strip())
print(text.replace(" ", "_"))
print(len(text))

text = text.strip().replace(" ", "_")

text

digital services act
___digital_services_act___
26

'digital_services_act'

## 6. Lists

A list stores multiple items in order.

Lists use square brackets: `[]`.

In [12]:
titles = ["Digital Services Act", "Online platform", "Content moderation"]

print(titles)
print(len(titles))
print(titles[0])
print(titles[1])

['Digital Services Act', 'Online platform', 'Content moderation']
3
Digital Services Act
Online platform

Python starts counting at zero. So `titles[0]` means the first item.

In [ ]:
print("First item:", titles[0])
print("Last item:", titles[-1])
print("First two items:", titles[:2])

Last item: Content moderation

## 7. Dictionaries

A dictionary stores key-value pairs.

Dictionaries use curly braces: `{}`.

In API work, dictionaries are everywhere: parameters, headers, JSON payloads, and rows for tables.

In [16]:
params = {
    "action": "query",
    "list": "search",
    "srsearch": "digital services act",
    "srlimit": 50,
    "format": "json",
}

print(params)
print(params["srsearch"])
print(params.keys())

{'action': 'query', 'list': 'search', 'srsearch': 'digital services act', 'srlimit': 50, 'format': 'json'}
digital services act
dict_keys(['action', 'list', 'srsearch', 'srlimit', 'format'])

Use square brackets when the key must exist. Use `.get()` when the key might be missing.

In [20]:
print(params["format"])
print(params.get("format"))
print(params.get("missing_parameter"))

json
json
None

## 8. Nested Dictionaries and Lists

API responses are often nested: dictionaries inside dictionaries, lists inside dictionaries, dictionaries inside lists.

This is why you see code like:

```python
payload["query"]["search"]
```

That means: go into `payload`, then into `"query"`, then into `"search"`.

In [21]:
payload = {
    "batchcomplete": True,
    "query": {
        "search": [
            {"pageid": 1, "title": "Digital Services Act", "wordcount": 1200},
            {"pageid": 2, "title": "Online platform", "wordcount": 900},
        ]
    },
}

search_results = payload["query"]["search"]
print(search_results)
print(search_results[0])
print(search_results[0]["title"])

[{'pageid': 1, 'title': 'Digital Services Act', 'wordcount': 1200}, {'pageid': 2, 'title': 'Online platform', 'wordcount': 900}]
{'pageid': 1, 'title': 'Digital Services Act', 'wordcount': 1200}
Digital Services Act

## 9. Loops

A loop repeats code for each item in a sequence.

Loops are used throughout the course scripts to process search results, links, pages, images, and records.

In [ ]:
for title in titles:
    print(title)

Digital Services Act
pause
Online platform
pause
Content moderation
pause

Indentation matters. The indented lines belong to the loop.

This is different from R, where braces often mark blocks. In Python, spaces do that job.

In [ ]:
rows = []

for item in search_results:
    row = {
        "pageid": item.get("pageid"),
        "title": item.get("title"),
        "wordcount": item.get("wordcount"),
    }
    rows.append(row)

print(rows)

## 10. If Statements

`if` lets code take different paths depending on a condition.

In [ ]:
status_code = 200

if status_code == 200:
    print("Request succeeded")
else:
    print("Something went wrong")

In [24]:
wordcount = 1200

if wordcount > 1000:
    print("Long page")
elif wordcount > 500:
    print("Medium page")
else:
    print("Short page")

Long page

## 11. Imports and Packages

Python has a standard library, but many useful tools come from packages.

In the course scripts, you often see imports like these:

In [25]:
from pathlib import Path
from pprint import pprint

import pandas as pd
import requests
from bs4 import BeautifulSoup

`import pandas as pd` means: load the pandas package and refer to it as `pd`.

If you get `ModuleNotFoundError`, Python is saying the package is not installed in the environment you are currently using.

## 12. File Paths with `Path`

The course scripts use `pathlib.Path` for file and folder paths.

This is more robust than manually pasting strings together.

In [ ]:
from pathlib import Path

outdir = Path("data")
raw_dir = outdir / "raw"
processed_dir = outdir / "processed"

print(raw_dir)
print(processed_dir)

data

In [ ]:
# mkdir creates folders.
# parents=True creates missing parent folders.
# exist_ok=True means it is okay if the folder already exists.

raw_dir.mkdir(parents=True, exist_ok=True)
processed_dir.mkdir(parents=True, exist_ok=True)

print(raw_dir.exists())
print(processed_dir.exists())

## 13. pandas DataFrames

A DataFrame is a table.

A common pattern in the course scripts is:

1. collect rows as dictionaries
2. put those dictionaries in a list
3. convert the list into a DataFrame

In [34]:
import pandas as pd

rows = [
    {"pageid": 1, "title": "Digital Services Act", "wordcount": 1200},
    {"pageid": 2, "title": "Online platform", "wordcount": 900},
]

df = pd.DataFrame(rows)
df.head()

   pageid                 title  wordcount
0       1  Digital Services Act       1200
1       2       Online platform        900

In [ ]:
print(df.head())
print(df["title"])
print(df[["title", "wordcount"]])

Save a DataFrame as a CSV file:

In [36]:
output_path
output_path = Path("data/processed/python_basics_example.csv")
df.to_csv(output_path, index=False)

print(output_path)

data/processed/python_basics_example.csv

Read it back:

In [37]:
df_read = pd.read_csv(output_path)
df_read

   pageid                 title  wordcount
0       1  Digital Services Act       1200
1       2       Online platform        900

## 14. API Responses: `response` vs `payload`

In the API scripts, this distinction is crucial:

- `response` is the HTTP response object
- `payload` is the parsed JSON data

Typical pattern:

```python
response = requests.get(API_URL, params=params, headers=headers, timeout=30)
response.raise_for_status()
payload = response.json()
```

The response object has things like status code, URL, headers, and text. The payload is usually dictionaries and lists.

In [ ]:
# This is a tiny fake payload shaped like an API response.
# It lets us practice JSON-style access without sending a live request.

payload = {
    "query": {
        "search": [
            {"pageid": 101, "title": "First result"},
            {"pageid": 102, "title": "Second result"},
        ]
    },
    "continue": {
        "sroffset": 2,
        "continue": "-||",
    },
}

pprint(payload)

In [ ]:
results = payload["query"]["search"]
continuation = payload.get("continue", {})

print(results)
print(continuation)

## 15. Dictionary Unpacking with `**`

In the API pagination code you see:

```python
request_params = {**params, **continuation}
```

This creates a new dictionary by combining two dictionaries.

In [ ]:
params = {
    "action": "query",
    "list": "search",
    "srsearch": "digital services act",
    "srlimit": 50,
}

continuation = {
    "sroffset": 50,
    "continue": "-||",
}

request_params = {**params, **continuation}
print(request_params)

This is used because the first request has no continuation fields, but later requests need the continuation values returned by the API.

## 16. From HTML Text to Data

The scraping scripts use a repeated workflow:

1. request a web page
2. receive HTML text
3. parse the HTML into a searchable structure
4. use selectors to find elements
5. extract text or attributes
6. store the extracted values in rows
7. turn rows into a table

The jump from "HTML text" to "data table" is where many scraping mistakes happen, so we will slow it down here.

### 16.1 What Is HTML?

HTML is the markup language used to structure web pages.

A web page is not just the text you see in the browser. Underneath, it contains tags such as:

| HTML piece | Meaning |
|---|---|
| `<div>...</div>` | generic container |
| `<span>...</span>` | small inline container |
| `<a href="...">...</a>` | link |
| `<p>...</p>` | paragraph |
| `<h1>...</h1>` | heading |
| `class="quote"` | class attribute used for styling and selection |
| `href="/author/Ada"` | link destination attribute |

A scraper usually does not "read the page" like a human. It searches this underlying structure.

In [ ]:
# This is a tiny artificial HTML page.
# In a real scraper, this text would usually come from response.text after requests.get().
html = """
<html>
  <body>
    <div class="quote" data-id="q1">
      <span class="text">A short quote.</span>
      <small class="author">Ada</small>
      <div class="tags">
        <a class="tag" href="/tag/api">api</a>
        <a class="tag" href="/tag/python">python</a>
      </div>
      <a class="author-link" href="/author/Ada">about Ada</a>
    </div>
  </body>
</html>
"""

print(html)

At this stage, `html` is only a Python string. Python does not yet understand it as a page structure.

We can check that with `type()`.

In [ ]:
print(type(html))

### 16.2 What BeautifulSoup Does

`BeautifulSoup` is a parser. A parser takes structured text and turns it into an object Python can search.

In the course scripts, this line appears often:

```python
soup = BeautifulSoup(html, "html.parser")
```

That means:

- take the HTML text stored in `html`
- parse it with Python's built-in HTML parser
- store the searchable result in an object called `soup`

The name `soup` is conventional. It is not magic; we could call it `parsed_page`, but most Python scraping examples use `soup`.

In [ ]:
from bs4 import BeautifulSoup

# BeautifulSoup turns HTML text into a searchable parse tree.
soup = BeautifulSoup(html, "html.parser")

print(type(soup))

`prettify()` is useful for inspection. It prints the nested HTML with indentation so we can see which elements are inside which other elements.

In [ ]:
# prettify() is not extraction. It is just a readable view of the parsed HTML.
print(soup.prettify())

### 16.3 Tags, Text, and Attributes

An HTML element usually has three things we care about:

1. the tag name, such as `a`, `div`, `span`
2. visible text, such as `A short quote.`
3. attributes, such as `class`, `href`, or `data-id`

For example:

```html
<a class="tag" href="/tag/api">api</a>
```

Here:

- tag name: `a`
- visible text: `api`
- class attribute: `tag`
- href attribute: `/tag/api`

In [ ]:
# Find the first link element on the page.
first_link = soup.select_one("a")

print("Whole element:", first_link)
print("Tag name:", first_link.name)
print("Visible text:", first_link.get_text(strip=True))
print("href attribute:", first_link.get("href"))
print("class attribute:", first_link.get("class"))

### 16.4 What Selectors Are

A selector is a small query that tells BeautifulSoup which HTML elements to find.

The course scripts use CSS selectors because they are concise and mirror what browser developer tools show.

Common selector patterns:

| Selector | Meaning |
|---|---|
| `a` | all `<a>` link elements |
| `a[href]` | all `<a>` elements that have an `href` attribute |
| `.quote` | all elements with class `quote` |
| `.text` | all elements with class `text` |
| `.tags a.tag` | all `<a class="tag">` links inside an element with class `tags` |
| `.quote .author` | an element with class `author` somewhere inside an element with class `quote` |
| `.result.card` | one element that has both classes `result` and `card` |
| `.result .card` | an element with class `card` inside an element with class `result` |

Important: the dot in `.quote` means "class", not visible text.

In [ ]:
# select_one() returns the first matching element.
print(soup.select_one(".quote"))

# select() returns a list of all matching elements.
print(soup.select("a"))

Use `select_one()` when you expect one element, such as the author inside one quote block.

Use `select()` when you expect several elements, such as all tag links.

In [ ]:
quote_block = soup.select_one(".quote")

# These searches happen inside quote_block, not across the whole page.
# This keeps fields from the same record together.
text_element = quote_block.select_one(".text")
author_element = quote_block.select_one(".author")
tag_elements = quote_block.select(".tags a.tag")
author_link = quote_block.select_one(".author-link")

print(text_element)
print(author_element)
print(tag_elements)
print(author_link)

### 16.5 Extracting Visible Text

`get_text()` extracts the visible text from an HTML element.

In the course scripts, you often see:

```python
element.get_text(" ", strip=True)
```

This means:

- get the visible text inside the element
- if there are nested pieces of text, join them with a space
- remove extra whitespace at the beginning and end

This is useful because HTML often contains line breaks and indentation that are not meaningful data.

In [ ]:
# get_text(" ", strip=True) extracts visible text, joins nested text with spaces,
# and removes leading/trailing whitespace.
quote_text = text_element.get_text(" ", strip=True)
author_name = author_element.get_text(" ", strip=True)

print(quote_text)
print(author_name)

The `strip=True` part is small but important. Without it, extracted text often contains unwanted spaces or line breaks.

In [ ]:
messy_html = "<p>\n    Lots of space around me    \n</p>"
messy_soup = BeautifulSoup(messy_html, "html.parser")
p = messy_soup.select_one("p")

print("Without strip:", repr(p.get_text()))
print("With strip:", repr(p.get_text(strip=True)))

### 16.6 Extracting Attributes

Not all useful data is visible text.

Links, image URLs, IDs, and metadata are often stored in attributes.

Use `.get("attribute_name")` to extract an attribute.

In [ ]:
# .get("href") asks for the href attribute.
# If the attribute is missing, .get() returns None instead of crashing.
author_href = author_link.get("href")
quote_id = quote_block.get("data-id")

print(author_href)
print(quote_id)

`.get()` is safer than square brackets when something might be missing.

Compare:

In [ ]:
print(author_link.get("href"))       # works
print(author_link.get("missing"))    # returns None

# This would raise a KeyError if uncommented, because the attribute does not exist:
# author_link["missing"]

### 16.7 Relative and Absolute URLs

HTML often stores links as relative paths:

```html
<a href="/author/Ada">about Ada</a>
```

The browser knows how to combine this with the current site. Python needs us to do that explicitly.

`urljoin()` combines the page URL and the relative path.

In [ ]:
from urllib.parse import urljoin

page_url = "https://quotes.toscrape.com/"
relative_href = author_link.get("href")
absolute_href = urljoin(page_url, relative_href)

print(relative_href)
print(absolute_href)

### 16.8 From One Record to a Row

Before looping over many records, extract one record carefully.

A row in a table is often just a dictionary where keys become column names.

In [ ]:
row = {
    "quote_id": quote_block.get("data-id"),
    "quote": text_element.get_text(" ", strip=True),
    "author": author_element.get_text(" ", strip=True),
    "author_url": urljoin(page_url, author_link.get("href")),
    "tags": [tag.get_text(" ", strip=True) for tag in tag_elements],
}

row

This row contains different kinds of extracted information:

- `quote_id`: an attribute from the quote container
- `quote`: visible text from `.text`
- `author`: visible text from `.author`
- `author_url`: an attribute converted into an absolute URL
- `tags`: several visible text values collected into a list

### 16.9 From Many Records to a DataFrame

Real pages usually contain repeated record containers: posts, search results, comments, products, videos, quotes, etc.

The standard pattern is:

1. create an empty list called `rows`
2. loop over repeated containers
3. extract fields from each container
4. append one dictionary per record
5. turn the list into a DataFrame

In [ ]:
# A slightly larger HTML example with two repeated quote records.
html_many = """
<html>
  <body>
    <div class="quote" data-id="q1">
      <span class="text">A short quote.</span>
      <small class="author">Ada</small>
      <div class="tags">
        <a class="tag" href="/tag/api">api</a>
        <a class="tag" href="/tag/python">python</a>
      </div>
      <a class="author-link" href="/author/Ada">about Ada</a>
    </div>

    <div class="quote" data-id="q2">
      <span class="text">Another short quote.</span>
      <small class="author">Grace</small>
      <div class="tags">
        <a class="tag" href="/tag/data">data</a>
      </div>
      <a class="author-link" href="/author/Grace">about Grace</a>
    </div>
  </body>
</html>
"""

soup_many = BeautifulSoup(html_many, "html.parser")

In [ ]:
import pandas as pd

rows = []

# .quote selects the repeated record containers.
for quote_block in soup_many.select(".quote"):
    # Search inside the current record container.
    # This avoids mixing the author from one record with the quote from another.
    text_element = quote_block.select_one(".text")
    author_element = quote_block.select_one(".author")
    tag_elements = quote_block.select(".tags a.tag")
    author_link = quote_block.select_one(".author-link")

    row = {
        "quote_id": quote_block.get("data-id"),
        "quote": text_element.get_text(" ", strip=True) if text_element else None,
        "author": author_element.get_text(" ", strip=True) if author_element else None,
        "author_url": urljoin(page_url, author_link.get("href")) if author_link else None,
        "tags": "|".join(tag.get_text(" ", strip=True) for tag in tag_elements),
        "tag_count": len(tag_elements),
    }

    rows.append(row)

# pd.DataFrame(...) turns a list of row dictionaries into a rectangular table.
quotes_df = pd.DataFrame(rows)
quotes_df

The `if text_element else None` pattern is defensive.

It means: if the element exists, extract the text; otherwise store `None` so missingness is visible instead of crashing the script.

### 16.10 Why This Is Useful for the Course Scripts

When you see this in the static scraping walkthrough:

```python
for quote_block in soup.select(".quote"):
    text = quote_block.select_one(".text")
    author = quote_block.select_one(".author")
```

read it as:

- find every repeated quote container
- handle one quote container at a time
- find the text field inside that quote
- find the author field inside that quote
- extract the values into one row

The exact same logic applies to less friendly pages:

- one search result card
- one post
- one video item
- one table row
- one moderation record

The hard part is identifying the correct repeated container and stable selectors.

### 16.11 Mini Exercise: Selector Reading

Using the two-record HTML above, answer:

- What does `.quote` select?
- What does `.tags a.tag` select?
- Why do we search inside `quote_block` rather than inside `soup_many` every time?
- Which extracted values come from visible text?
- Which extracted values come from attributes?
- What would happen if one quote had no author link?

## 17. Functions You Define Yourself

The runnable workflow scripts define functions so code can be reused.

A function definition starts with `def`.

In [ ]:
def make_page_url(pageid):
    """Return a browser URL for a Wikipedia page ID."""
    return f"https://en.wikipedia.org/?curid={pageid}"

print(make_page_url(101))
print(make_page_url(102))

Functions can have default arguments.

In [ ]:
def describe_collection(query, page_size=50, max_pages=2):
    maximum = page_size * max_pages
    return {
        "query": query,
        "page_size": page_size,
        "max_pages": max_pages,
        "maximum_requested_results": maximum,
    }

print(describe_collection("digital services act"))
print(describe_collection("platform governance", page_size=25, max_pages=4))

## 18. Common Error Messages

These errors are not signs that you are bad at Python. They are normal signals that something needs checking.

### `ModuleNotFoundError`

Python cannot find a package in the current environment.

Common fix: install the package in the environment you are actually using.

### `KeyError`

You asked for a dictionary key that does not exist.

Common fix: inspect `.keys()` or use `.get()`.

### `TypeError: string indices must be integers`

You are treating a string like a dictionary.

Common situation: using `response.text` when you meant `response.json()`.

### `JSONDecodeError`

You tried to parse JSON, but the response was not valid JSON.

Common fix: inspect `response.status_code`, `response.headers`, and `response.text`.

### `IndentationError`

Python expected indentation to match the block structure.

Common situation: pasting a multi-line loop into the interactive prompt in pieces.

In [ ]:
# Example of checking dictionary keys before extracting fields:

record = {"pageid": 101, "title": "First result"}

print(record.keys())
print(record.get("timestamp"))       # returns None instead of crashing
print(record.get("timestamp", "not available"))

## 19. Mini Exercise: Read a Course-Script Pattern

Read this pattern and explain what each object is:

In [ ]:
params = {
    "action": "query",
    "list": "search",
    "srsearch": "digital services act",
    "srlimit": 50,
    "format": "json",
    "formatversion": 2,
}

rows = []

for item in payload["query"]["search"]:
    row = {
        "pageid": item.get("pageid"),
        "title": item.get("title"),
    }
    rows.append(row)

example_df = pd.DataFrame(rows)
example_df

Questions:

- What type of object is `params`?
- What type of object is `rows` at the start?
- What does the loop iterate over?
- What type of object is `row`?
- What does `rows.append(row)` do?
- What does `pd.DataFrame(rows)` create?

## 20. Key Takeaways

For this course, the most important Python patterns are:

- assign meaningful names to objects
- read dictionaries with keys
- loop over lists of records
- build lists of row dictionaries
- convert rows to DataFrames
- distinguish raw responses from processed tables
- save outputs deliberately
- read error messages as clues

You do not need to memorize everything. You need to recognize the patterns when they appear in the scripts.